version: '3.1'

services:
  mysql:
    image: mysql:8.0
    container_name: dockerMySQL # https://qiita.com/Keyskey/items/a1baa04d6850cc50727c
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 13306:3306
    volumes:
      - ./.data:/var/lib/mysql
    networks:
      - testnetwork
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 1s
      timeout: 1s
      retries: 20
      start_period: 1s

  backend_server:
    container_name: backend_server
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - testnetwork

networks:
  testnetwork:
    name: testnetwork
